"use strict";
exports.__esModule = true;
var animal_1 = require("./animal");
var zoologico_1 = require("./zoologico");
var conjunto = [];
var toto = new animal_1.animal(2, 3, 'Cachorro');
var gato = new animal_1.animal(3, 2, 'Preto');
var coelho = new animal_1.animal(3, 2, 'Rapido');
var zoologico = new zoologico_1.zoo('Sapucaia', conjunto);
conjunto.push(toto);
conjunto.push(gato);
conjunto.push(coelho);
console.log(zoologico);
